language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - which python
  - which pip
  - pip install -U pip

install:
  - pip install .
  - pip install -r requirements-dev.txt
  - pip install keyrings.alt>=3.1

script:
  - set -e
  - coverage run --source pgcli -m py.test
  - cd tests
  - behave
  - cd ..
  # check for changelog ReST compliance
  - rst2html.py --halt=warning changelog.rst >/dev/null
  # check for pep8 errors, only looking at branch vs master. If there are errors, show diff and return an error code.
  - pep8radius master --docformatter --diff --error-status
  - set +e

after_success:
  - coverage combine
  - codecov

notifications:
  webhooks:
    urls:
      - YOUR_WEBHOOK_URL
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

services:
  - postgresql

addons:
  postgresql: "9.3"
